### ISSUE TITLE
Can not provision IBM service with a service id

### ISSUE THREAD

**Issue by qibobo** [IBM/cloud-operators#98] opened 2020-03-11 05:22 UTC
I used a IBM cloud service id(Administrator role)'s apikey to provision a service by using cloud-operator the latest release, the error threw:
`Request failed with status code: 400, BXNIM0106E: Validation of property 'response_type' with value '[uaa, cloud_iam]' failed. Valid values: 'cloud_iam, delegated_refresh_token'`

I have verified that with the service id's api key, I can successfully provision service by using ibmcloud cli.
So does cloud-operator support service id?

**Comment by qibobo** [comment] 2020-03-11 15:42
Seems the similar issue in terraform-provider-ibm https://github.com/IBM-Cloud/terraform-provider-ibm/issues/591
The root cause is the old version of bluemix-go.

**Comment by dwakeman** [comment] 2020-03-13 02:01
I need to be able to use service IDs as well, and I am very interested in the resolution of this issue. 

Thanks!

**Comment by qibobo** [comment] 2020-03-13 09:51
@vazirim 
Any updates?

**Comment by vazirim** [comment] 2020-03-13 18:19
@qibobo I am unable to reproduce this problem.
Can you please retry and see if you still have the problem (it could be that bluemix was not cooperating when you last tried this)?

@dwakeman Did you try using a serviceid and it didn't work?

**Comment by dwakeman** [comment] 2020-03-13 18:59
No, just happened to be viewing the issues list and saw this.  I will test it out.

**Comment by vazirim** [comment] 2020-03-13 19:05
All you need is for your seed-secret to contain the api-key of the serviceId, and to give it proper access permissions in iam.

**Comment by vazirim** [comment] 2020-03-13 20:31
@qibobo I just observed this error (in the logs of the controller) in a completely different situation (doesn't have anything to do with serviceids). However, it still seems to work.

**Comment by vazirim** [comment] 2020-03-13 21:51
I was able to reproduce the bug and fixed it. Fix will be available in the next release.

**Comment by qibobo** [comment] 2020-03-16 01:48
@vazirim 
When I used the latest version(v1.0.5),  I still can not provision service successfully. Now the error is `Request failed with status code: 400, ServerErrorResponse: {"message":"The resource group 0000161cdb364e489a09f7f971a34363 is inactive with state: SUSPENDED","status_code":400,"transaction_id":"bss-5a2dc634bdce8422"}`
I have tried serval times and it always failed with the same error.

And I have manually checked my service id could provision service.

**Comment by vazirim** [comment] 2020-03-16 01:58
The latest release does not address this issue.

That is also the error that I see. I have been looking at the `ibmcloud` cli to see what they are doing differently. They are using a different library for starters (ibmcloud-cli-sdk) instead of bluemixgo. In the long run we need to understand which library to use. In the shorter term, I will try to find out what REST calls need to happen on IAM and do those directly, bypassing bluemixgo. Please don't expect a rapid fix for this.

**Comment by vazirim** [comment] 2020-03-18 00:25
Fixed in v0.1.6

**Comment by qibobo** [comment] 2020-03-19 07:29
It works now. Thank you!

**Closed** 2020-03-19 07:29 UTC
Labels: done
