### ISSUE TITLE
Operator creates an excessive number of policy entries

### ISSUE THREAD

**Issue by seansund** [IBM/cloud-operators#86] opened 2020-03-01 14:30 UTC
Each time a binding CR is created, it creates a corresponding credential in the service even if a credential of the same name already exists on that service.

Each credential, in turn, creates an access policy against the account.

An account has a hard limit of 600 policies that can be created. In several accounts, using the IBM Cloud operator on a medium scale deployment has resulted in policy limit to be hit.

This may be compounded by some other issue in the Operator where the credentials are not cleaned up properly when the service is destroyed and/or the Operator creating orphaned policies when it removes/re-creates the binding.

**Comment by vazirim** [comment] 2020-03-01 15:15
@seansund The Binding and Service objects are independent of each other. Deleting a Service object does not cause the deletion of the Binding object because there is no ownership relationship. We removed this relationship to allow another user (from Garage) to create Service and Bindings in different namespaces. Having the ownership relationship would have taken care of deleting the Binding when the Service is deleted. However, Kubernetes doesn't allow objects with ownership relationships to be created in different namespaces. It has its own garbage collector, which rectifies this situation at random by removing the Binding. I recognize that we have a garbage collection issue here when the Service is deleted. In this case, the Binding waits for the Service to be recreated in order to recreate its credentials. Perhaps in the cases where the Binding and Service are in the same namespace, we can add ownership relation to alleviate this issue...

The Binding controller shouldn't recreate a credential with the same name. Will look into this. Could you please send me a yaml for the Service and Binding where you see this behavior?

**Comment by vazirim** [comment] 2020-03-02 18:56
@seansund I am unable to reproduce the issue with the binding controller recreating credentials with the same name. Please send me yaml or the type of service for which this is happening. TIA

**Comment by vazirim** [comment] 2020-03-04 14:40
@seansund We are going to implement a new feature to address the problem with the excessive access policies. The feature will allow users to define aliases on Binding resources as well. So when there are many Bindings with the same name in different namespaces, rather than creating a new credential for each on the service, these Bindings can simply "alias" an existing credential. 

The alias would be specified in the spec on Binding as a name of a credential on the corresponding service. If this name is unique, then it will succeed (and set the ID in Binding status to that), if it is not unique then it will fail. We can also have an optional keyID field to allow the user to specify which credential to alias when there are more than one with the same name.

Please let me know asap if this addresses your issue (planning on implementing it today). Thanks!

**Comment by vazirim** [comment] 2020-03-12 19:27
Fixed in v0.1.5

**Closed** 2020-04-02 19:09 UTC
Labels: done
