### ISSUE TITLE
OOMKilled error on ibmcloud-operator-controller-manager

### ISSUE THREAD

**Issue by arturobrzut** [IBM/cloud-operators#260] opened 2021-09-07 12:27 UTC
Environment:
OS:
Version: IAF 1.2.0-RC0, CS latest-validated
Cluster: ROKS OCP 4.7.23
Browser:

Description:
I constantly see this, seems to be a resurface of #4271

state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 5m0s restarting failed container=manager
            pod=ibmcloud-operator-controller-manager-5c4d7c974b-m2z2t_ibm-common-services(8ff08114-5b17-4094-acd8-4d4963aabc01)
      imageID: >-
        docker.io/cloudoperators/ibmcloud-operator@sha256:9b09e8a419f03915b9673fa4445dfae1520e467249fb55f54a93895419c13f7a
      image: 'docker.io/cloudoperators/ibmcloud-operator:1.0.11'
      lastState:
        terminated:
          exitCode: 137
          reason: OOMKilled
          startedAt: '2021-09-06T16:31:34Z'
          finishedAt: '2021-09-06T16:32:28Z'
          containerID: >-
            cri-o://2c0ce8efadd4bd6159613b26d1e7ad1f251fb4a84b7fb6ec39657640a0ffbb94

**Comment by arturobrzut** [comment] 2021-09-07 12:28
![image](https://user-images.githubusercontent.com/54812713/132344470-bd549286-a86a-4a79-b982-68e367f0fe4a.png)

**Comment by JohnStarich** [comment] 2021-09-17 18:35
Duplicate of https://github.com/IBM/cloud-operators/issues/199
Closing in favor of that one.

**Closed by JohnStarich** 2021-09-17 18:35 UTC
